apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-website-deployment
  namespace: gandharvi-dev
  labels:
    app: food-website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: food-website
  template:
    metadata:
      labels:
        app: food-website
    spec:
      containers:
      - name: food-website-container
        # Yeh raha exact image link jo OpenShift khud use karega
        image: image-registry.openshift-image-registry.svc:5000/gandharvi-dev/food-image:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10