apiVersion: v1
kind: Service
metadata:
  name: food-service
  namespace: gandharvi-dev
spec:
  selector:
    app: food-website
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
  
